references:

  commands:

    test: &run_phpunit
      name: run phpunit
      command: phpdbg -qrr vendor/bin/phpunit --coverage-html /tmp/build/coverage-report test

    install_php_extensions: &install_php_extensions
      name: run install_php_extensions
      command: |
        sudo apt-get update && sudo apt-get -y install zlib1g-dev unzip libpng-dev
        sudo docker-php-ext-install pdo_mysql zip gd

  caches:

    restore_composer_install: &restore_composer_install
      keys:
        - h1r0-2525-php-cs-fixer-composer-install-{{ checksum "composer.lock" }}

      save_composer_install: &save_composer_install
        key: h1r0-2525-php-cs-fixer-composer-install-{{ checksum "composer.lock" }}
        paths:
          - vendor

  steps:

    test: &test
      - checkout
      - restore_cache: *restore_composer_install
      - run: *install_php_extensions
      - run: composer install --no-interaction
      - save_cache: *save_composer_install
      - run: *run_phpunit
      - store_artifacts:
          path: /tmp/build/coverage-report

version: 2.1

jobs:

  php72:
    docker:
      - image: circleci/php:7.2
    steps: *test

  php73:
    docker:
      - image: circleci/php:7.3
    steps: *test

  php74:
    docker:
      - image: circleci/php:7.4
    steps: *test

workflows:

  version: 2

  tests:

    jobs:

      - php72:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

      - php73:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      
      - php74:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
